main:
  - name: Főoldal
    url: ""
    weight: 1
  # - name: Szolgáltatások
  #   url: "#service"
  #   weight: 2
  # - name: Képesítés
  #   url: "#resume"
  #   weight: 3
  - name: Rólunk
    url: "#about"
    weight: 4
  - name: Termékek
    url: "#product"
    weight: 5
  - name: Ajánlások
    url: "#testimonial"
    weight: 6
  - name: Referenciamunkák
    url: "#blog"
    weight: 7
sitemap:
  - name: Főoldal
    url: ""
    weight: 1
  - name: Kapcsolat
    url: "contact"
    weight: 2
  - name: Termékek
    url: "product"
    weight: 3
  - name: Referenciamunkák
    url: "blog"
    weight: 4
